apiVersion: v1
kind: Pod
metadata:
  name: multitool-test
spec:
  containers:
  - name: multitool-test
    image: wbitt/network-multitool:alpine-minimal
    ports:
    - containerPort: 1180
    env:
    - name: HTTP_PORT
      value: "1180"
