apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-svc
spec:
  type: ClusterIP
  selector:
    app: nginx-multitool
  ports:
  - name: nginx
    port: 80
    targetPort: 80
  - name: multitool
    port: 1180
    targetPort: 1180
